In [43]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [44]:
"""
X =features,features variables ,data
Y=labels,targets,target variables

"""

heart_disease=pd.read_csv(r"C:\Users\murat\OneDrive\Masaüstü\VS_CODE\ML\heart-disease-scikit.csv")                                      
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

np.random.seed(42)

X=heart_disease.drop("target",axis=1)
y=heart_disease["target"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

clf=RandomForestClassifier(n_estimators=1000)

clf.fit(X_train,y_train) # trainig the machine learning model
print(f"model accuracy : %{clf.score(X_test,y_test)*100:.2f}")

model accuracy : %86.89


Make predictions with our model

In [45]:
# Use a trained model
# 1-predict() 2-predict_proba()
X_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [46]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [47]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [48]:
# Comparison
y_preds=clf.predict(X_test)
np.mean(y_preds==y_test)

0.8688524590163934

In [49]:
a=clf.predict(X_test)
b=np.array(y_test)
X=pd.DataFrame({"X_test":a,"y_test":b})
X.head(10)      

X_test  y_test
0       0       0
1       1       0
2       1       1
3       0       0
4       1       1
5       1       1
6       1       1
7       0       0
8       0       0
9       1       1

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(a,b)

0.8688524590163934

In [51]:
# predict_proba() returns probabilitites of a classification label
clf.predict_proba(X_test[:5])

array([[0.894, 0.106],
       [0.435, 0.565],
       [0.455, 0.545],
       [0.871, 0.129],
       [0.23 , 0.77 ]])

In [54]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import fetch_california_housing

housing=fetch_california_housing()
housing_df=pd.DataFrame(housing["data"],columns=housing["feature_names"])
housing_df["MedHouseVal"]=housing["target"]
housing_df["target"]=housing["target"]
housing_df=housing_df.drop("MedHouseVal",axis=1)

np.random.seed(42)

X=housing_df.drop("target",axis=1)
y=housing_df["target"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

model=RandomForestRegressor(n_estimators=100)
model.fit(X_train,y_train)
y_preds=model.predict(X_test)

In [57]:
y_preds[:10]

array([0.4943   , 0.7642   , 4.9346864, 2.56113  , 2.29764  , 1.6625701,
       2.34127  , 1.66352  , 2.48233  , 4.843458 ])

In [58]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [64]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds)


0.3267155795542638