In [90]:

import matplotlib.pyplot as pl
import numpy as np
import pandas as pd

What we are going to cover 
0.An end to end Scikit learn workflow
1.Getting the data ready
2.Choose the right estimator/algorithm for our problems
3.Fit the model/algorithm and use ist to make predictions on our data
4.Evaluating the model
5.Improve the model
6.Save and load the trained model
7.Putting it all together


0.An end to end Scikit learn workflow

In [91]:
heart_disease=pd.read_csv(r"C:\Users\murat\OneDrive\Masaüstü\VS_CODE\ML\heart-disease-scikit.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [92]:
#Create X features matrix
x=heart_disease.drop("target",axis=1)
#Create y (labels)
y=heart_disease["target"]

In [93]:
##2.Choose the right estimator/algorithm for our problems
#----------------------------------------------------------------
#import sklearn
#sklearn.show_versions()
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [94]:
##3.Fit the model/algorithm and use ist to make predictions on our data
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [95]:
clf.fit(X_train,y_train)

RandomForestClassifier()

In [96]:
#make a prediction
y_preds=clf.predict(X_test)
y_preds

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [97]:
#4.Evaluating the model
clf.score(X_train,y_train)

1.0

In [98]:
clf.score(X_test,y_test)

0.819672131147541

In [99]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.78      0.81      0.79        26
           1       0.85      0.83      0.84        35

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61



In [100]:
confusion_matrix(y_test, y_preds),accuracy_score(y_test, y_preds)

(array([[21,  5],
        [ 6, 29]], dtype=int64),
 0.819672131147541)

In [101]:
#5.Improve the model
np.random.seed(42)
for i in range(10,100,10):
    print(f"trying model with {i} estimators...")
    clf=RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f"model accuracy : {clf.score(X_test,y_test)*100:.2f}%")

trying model with 10 estimators...
model accuracy : 80.33%
trying model with 20 estimators...
model accuracy : 81.97%
trying model with 30 estimators...
model accuracy : 78.69%
trying model with 40 estimators...
model accuracy : 83.61%
trying model with 50 estimators...
model accuracy : 86.89%
trying model with 60 estimators...
model accuracy : 85.25%
trying model with 70 estimators...
model accuracy : 81.97%
trying model with 80 estimators...
model accuracy : 81.97%
trying model with 90 estimators...
model accuracy : 83.61%


In [102]:
#6.Save and load the trained model
import pickle
pickle.dump(clf,open("random_forest_class.pkl","wb"))

In [103]:
laoded_model=pickle.load(open("random_forest_class.pkl","rb"))
laoded_model.score(X_test,y_test)


0.8360655737704918

1-Getting our data ready to be used with ML 

Three main things we have to do:
1.Splitting the data into features and labels ("X,"y")
2.Filling or disregarding missing values 
3.Converting non-numerical values to numerical values

In [104]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [105]:
X=heart_disease.drop("target",axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [106]:
y=heart_disease["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [107]:
#Split the data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [108]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

make sure it's all numerical

In [109]:
car_sales=pd.read_csv(r"C:\Users\murat\OneDrive\Masaüstü\VS_CODE\ML\car-sales-extended.csv")
len(car_sales),car_sales.head()

(1000,
      Make Colour  Odometer (KM)  Doors  Price
 0   Honda  White          35431      4  15323
 1     BMW   Blue         192714      5  19943
 2   Honda  White          84714      4  28343
 3  Toyota  White         154365      4  13434
 4  Nissan   Blue         181577      3  14043)

In [110]:
X=car_sales.drop("Price",axis=1)
y=car_sales["Price"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [111]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
#Turn categories into numbers
from sklearn.preprocessing import OneHotEncoder#turn into numbers
from sklearn.compose import ColumnTransformer

categories=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categories)]
,remainder="passthrough")
transformed_X=transformer.fit_transform(X)
transformed_X


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [112]:
#Also there is pd.get_dummies()
np.random.seed(42)
#recreate the data splits with numerical data
X_train, X_test, y_train, y_test =train_test_split(transformed_X,y,test_size=0.2)
model.fit(X_train, y_train)
model.score(X_test, y_test)


0.3235867221569877

What if there were missing values ?
Option 1

In [113]:
#1-Fill them with some values
#2-Remove the samples with missing data altogether
car_sales_missing=pd.read_csv(r"C:\Users\murat\OneDrive\Masaüstü\VS_CODE\ML\car-sales-extended-missing-data.csv")

In [114]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [115]:
Xx=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]


In [116]:
from sklearn.preprocessing import OneHotEncoder#turn into numbers
from sklearn.compose import ColumnTransformer

categories=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categories)]
,remainder="passthrough")
transformed_X=transformer.fit_transform(Xx)
transformed_X

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

In [117]:
# Fill the columns
car_sales_missing["Make"].fillna("missing",inplace=True)
car_sales_missing["Colour"].fillna("mising",inplace=True)
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(),inplace=True)
car_sales_missing["Doors"].fillna(4,inplace=True)

In [118]:
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [119]:
#Remove rows with missing price values from
car_sales_missing.dropna(inplace=True)
car_sales_missing.isna().sum()


Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [120]:
X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]

In [121]:
#Let's do encoding again without missing values

from sklearn.preprocessing import OneHotEncoder#turn into numbers
from sklearn.compose import ColumnTransformer

categories=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categories)]
,remainder="passthrough")
transformed_X=transformer.fit_transform(X)
transformed_X

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

Option 2 ,Fill with Scikit-learn

In [128]:
car_miss=pd.read_csv(r"C:\Users\murat\OneDrive\Masaüstü\VS_CODE\ML\car-sales-extended-missing-data.csv")

In [129]:
car_miss.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [130]:
car_miss.dropna(subset=["Price"],inplace=True)
car_miss.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [133]:
Xx=car_miss.drop("Price",axis=1)
y=car_miss["Price"]
np.random.seed(42)
Xx_train, Xx_test, y_train, y_test = train_test_split(Xx,
                                                    y,
                                                    test_size=0.2)

In [135]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
# Fill categorical values with "missing" and numerical values with mean 
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# Define columns
cat_features = ["Make", "Colour"]
door_feature = ["Doors"]
num_features = ["Odometer (KM)"]

# Create an imputer (something that fills missing data)
imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", door_imputer, door_feature),
    ("num_imputer", num_imputer, num_features)
])

# Fill train and test values separately
filled_X_train = imputer.fit_transform(Xx_train) # fit_transform imputes the missing values from the training set and fills them simultaneously
filled_X_test = imputer.transform(Xx_test) # tranform takes the imputing missing values from the training set and fills the test set with them

# Check filled X_train
filled_X_train

array([['Honda', 'White', 4.0, 71934.0],
       ['Toyota', 'Red', 4.0, 162665.0],
       ['Honda', 'White', 4.0, 42844.0],
       ...,
       ['Toyota', 'White', 4.0, 196225.0],
       ['Honda', 'Blue', 4.0, 133117.0],
       ['Honda', 'missing', 4.0, 150582.0]], dtype=object)

In [136]:
car_miss_filled_train=pd.DataFrame(filled_X_train,columns=["Make","Colour","Doors","Odometer (KM) "])
car_miss_filled_train.isna().sum()

Make              0
Colour            0
Doors             0
Odometer (KM)     0
dtype: int64

In [ ]:
# Now split the data again with filled X dataset and use encoder 