**Numpy**

In [ ]:
import numpy as np

In [ ]:
list1=[[1,2,3],[4,5,6]]
array_list1=np.array(list1)

print(list1)
print(array_list1)

a=np.ones((7,7))+5
print(a)

b=np.linspace(0,10,100)
print(b)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
[[6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]]
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.4646464

In [ ]:
random=np.random.rand(4,4)
print("random sayılar",random)

random2=np.random.randn(5,5)
print("random sayılar",random2)

random3=np.random.randint(1,5,40)
print("integer random sayılar",random3)
print(random3.shape)#resize çarpımı shape e eşit olmalı

random3_reshape=random3.reshape(8,5)
print(random3_reshape)

max_random3=random3.max()
print("random3 teki en büyük eleman",max_random3)

min_random3=random3.min()
print("random3 teki en küçük eleman",min_random3)

max_random3_index_no=random3.argmax()
min_random3_index_no=random3.argmin()

print("en büyük elemanın indexi",max_random3_index_no)
print("en küçük elemanın indexi",min_random3_index_no)

random sayılar [[0.2548152  0.32151779 0.82951295 0.29267844]
 [0.92441934 0.26109998 0.13162822 0.61345419]
 [0.70413912 0.65926711 0.60559108 0.68312083]
 [0.11941325 0.48750942 0.24670847 0.7667616 ]]
random sayılar [[ 0.90523966 -0.11690884 -0.39573608  0.67326348 -0.58894855]
 [-0.10967237 -0.58034102  0.27096101  0.23452665  1.8223391 ]
 [ 0.75815828  1.4788965   0.21867371  0.28458323 -1.64394682]
 [-0.1439497  -2.49469215 -0.81636526 -0.40015092 -1.01872804]
 [-1.69878666 -0.81834405  0.20901597 -1.82923347  2.42165036]]
integer random sayılar [4 2 1 3 1 3 1 1 3 4 4 3 3 3 4 4 2 3 1 1 1 1 1 3 2 3 4 4 2 4 2 3 3 1 3 1 3
 4 3 3]
(40,)
[[4 2 1 3 1]
 [3 1 1 3 4]
 [4 3 3 3 4]
 [4 2 3 1 1]
 [1 1 1 3 2]
 [3 4 4 2 4]
 [2 3 3 1 3]
 [1 3 4 3 3]]
random3 teki en büyük eleman 4
random3 teki en küçük eleman 1
en büyük elemanın indexi 0
en küçük elemanın indexi 2


In [ ]:
range_array=np.arange(0,10)
print(range_array)
print(range_array[:4])

slice_array=range_array[:4]
slice_array_changed=slice_array.copy()
slice_array_changed[:]=100
print(slice_array_changed)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[100 100 100 100]


In [ ]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=array_2d.sum(axis=0)
print(a)#sütunların toplamı,sum of the value in columns

[12 15 18]


**Torch**

In [ ]:
import torch

In [ ]:
array=np.array([[1,2,3],[4,5,6]])
array_tensor=torch.from_numpy(array)
print("numpy array",array)
print("numpy array converted to torch tensor",array_tensor)

array=array.reshape(2,3)
array_tensor=torch.from_numpy(array)
print("reshaped",array)
print("reshaped :  {} type  : {}".format(array_tensor,array_tensor.dtype))

numpy array [[1 2 3]
 [4 5 6]]
numpy array converted to torch tensor tensor([[1, 2, 3],
        [4, 5, 6]])
reshaped [[1 2 3]
 [4 5 6]]
reshaped :  tensor([[1, 2, 3],
        [4, 5, 6]]) type  : torch.int64


In [ ]:
new_arr=np.array([1,2,3])
tensor_dytpe_int=torch.tensor(new_arr)
tensor_dytpe_float=torch.Tensor(new_arr)
print(tensor_dytpe_int,tensor_dytpe_int.dtype)
print(tensor_dytpe_float,tensor_dytpe_float.dtype)

a=torch.arange(0,40,4,dtype=torch.float32)

a=a.reshape(2,5)#view(2,5) de olur
#rand randn randint linspace ones zeros hepsi torch'da da var
print("a",a)
print("seçilen yerler",a[:2,3:5])   

#matrix çarpımı
x=torch.tensor([[1,2,3],[4,5,6]])
y=torch.tensor([[4,5],[7,8],[9,11]])

matrix_carpımı=torch.mm(x,y)# x @ y aynı işi yapıyor
print("matrix çarpımı",matrix_carpımı)
#x.numel() toplam elemanı verir len sadece satır sayısını

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32
a tensor([[ 0.,  4.,  8., 12., 16.],
        [20., 24., 28., 32., 36.]])
seçilen yerler tensor([[32., 36.]])
matrix çarpımı tensor([[ 45,  54],
        [105, 126]])
