In [283]:
import numpy as np

In [284]:
#----------------------------------------Datatypes and attributes----------------------------------------
#ndarray 
a1=np.array([1,2,3])
a1
a2=np.array([[1,2,3,6], [4,6,5,9]])    # ([[[]]]) --> 3 dimensional
a2.ndim
a2.shape
a2.size

8

In [285]:
import pandas as pd #creating a dataframe with numpy array
df=pd.DataFrame(a2)
df


0  1  2  3
0  1  2  3  6
1  4  6  5  9

In [286]:
ones=np.ones((6,3),float)
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [287]:
zeros=np.zeros((4,5),int)
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [288]:
range_array=np.arange(0,100,10)
range_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [289]:
random=np.random.rand(3,4)
random

array([[0.71932412, 0.41299183, 0.90642327, 0.18045162],
       [0.74111887, 0.42237404, 0.42645357, 0.63437987],
       [0.5229062 , 0.41488598, 0.00142688, 0.09226235]])

In [290]:
randomint=np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
randomint
randd=np.random.randint(0,10,size=(4,5))
randd

array([[3, 4, 5, 3, 0],
       [4, 8, 6, 7, 2],
       [7, 3, 8, 6, 6],
       [5, 6, 5, 7, 1]])

In [291]:
#Pseudo random numbers
np.random.seed(7)
seed=np.random.random((5,3))
seed

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [292]:
##----------------------------------------Viewing arrays and matrices----------------------------------------
np.unique(randd)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [293]:
randd

array([[3, 4, 5, 3, 0],
       [4, 8, 6, 7, 2],
       [7, 3, 8, 6, 6],
       [5, 6, 5, 7, 1]])

In [294]:
randd[2][1]
randd[:3,:3]

array([[3, 4, 5],
       [4, 8, 6],
       [7, 3, 8]])

In [295]:
fourd=np.random.randint(10,size=(1,2,3,4)) # 4 means amount of rows elements , 3 means amount of columns elements 
                                           #, 2 means how many this matrices are , 1 means how many times repeats these matrices 
fourd

array([[[[3, 5, 8, 8],
         [7, 5, 0, 0],
         [2, 8, 9, 6]],

        [[4, 9, 7, 3],
         [3, 8, 3, 0],
         [1, 0, 0, 6]]]])

In [296]:
fourd.ndim
# Get the first elements of the inner most arrays , returns columns !
fourd[:,:,:,0]

array([[[3, 7, 2],
        [4, 3, 1]]])

In [297]:
#----------------------------------------Manipulating and comparing arrays----------------------------------------
#Arithmetic
a3=np.array([1,2,3])
ones2=np.ones(3)
a3+ones2


array([2., 3., 4.])

In [298]:
a4=np.array([(2,3,4),(1,2,3)])
a4*a3

array([[ 2,  6, 12],
       [ 1,  4,  9]])

In [299]:
a4.shape
a5=np.array([[[(1,2,3),(4,5,6),(7,8,9),(10,11,12)]]])
a5.shape
a4*a5 

ValueError: operands could not be broadcast together with shapes (2,3) (1,1,4,3) 

In [ ]:
# Let's fix that error 
# Go to the section of the Reshaping and transposing !!!!!
"""a5=np.reshape(a5,(6,1))
a5.shape # reshaped"""

(6, 1)

In [ ]:
##----------------------------------------Aggreagation----------------------------------------
massive_array=np.random.random(10000)

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)   # 500 times faster as python sum does

2.23 ms ± 363 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
13.6 µs ± 360 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
#----------------------------------------Reshaping and transposing----------------------------------------
a6=np.array([[1,2,3], [4,5,6]])
a7=np.random.randint(10,size=(2,3,3))
a7*a6
   

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [301]:
# Let's fix this
a6.shape
a6_reshaped=a6.reshape(2,3,1)
a6_reshaped.shape

(2, 3, 1)

In [ ]:
a6_reshaped*a7

array([[[ 7,  7,  9],
        [ 6,  0, 14],
        [21, 21,  0]],

       [[20, 16, 12],
        [ 5, 15,  5],
        [18, 24, 18]]])

In [302]:
# Transpose
a6_transposed=a6_reshaped.T
a6_transposed.shape

(1, 3, 2)

In [303]:
##----------------------------------------Dot product vs element wise----------------------------------------
np.random.seed(0)
exp1=np.random.randint(10,size=(5,3))
exp2=np.random.randint(10,size=(5,3))

In [304]:
exp2*exp1 # element wise

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [305]:
exp1.dot(exp2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [307]:
# Inside numbers must match --> (5,3) and (3,5) are okey let's use transpose then 
exp3=np.dot(exp1,exp2.T)
exp3.shape

(5, 5)

In [308]:
##----------------------------------------Comparison operators----------------------------------------
# a1<a2  a1>5  a1>=a2  a3<=a1 a2==a1
##--------------------------------Sorting arrays--------------------------------
random11=np.random.randint(10,size=(2,3))
random11=np.sort(random11)
random11


array([[2, 3, 8],
       [1, 3, 3]])

In [322]:
exp4=np.array([[(1,2,3),(4,9,6)]])
exp4=np.argsort(exp4)
exp4


array([[[0, 1, 2],
        [0, 2, 1]]], dtype=int64)

In [325]:
np.argmax(exp4)
np.argmin(exp4)
np.argmax(exp4,axis=0)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [330]:
##--------------------------------from images to numpy array--------------------------------
from matplotlib.image import imread
panda=imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [331]:
panda.size,panda.shape,panda.ndim

(24465000, (2330, 3500, 3), 3)